### ISSUE TITLE
Add shortcode support

### ISSUE THREAD

**Issue by jbmoelker** [voorhoede/playbook#37]
It would be great if we could insert rich media into our Playbook, like for instance a YouTube Playlist of all the code talks. Shortcodes ([popularised by Hugo](https://gohugo.io/content-management/shortcodes/)) offer a way to do this. For example embedding this playlist https://www.youtube.com/playlist?list=PL597E0BDDC1D74ED2 could be done in markdown as follows:

```md
[[ YouTube list="PL597E0BDDC1D74ED2" ]]
```

or 

```md
{{< YouTube list="PL597E0BDDC1D74ED2" >}}
```

depending on the shortcode notation.

Possible helper library: https://github.com/djm/remark-shortcodes

**Comment by Siilwyn** [comment]
Wouldn't Vue component accomplish this?

**Comment by jbmoelker** [comment]
Yes. The only difference is that I'd like the contents of Paper documents to be independent od what we consume them with. So if we swap out VuePress for Docusaurus, we wouldn't need to update all our content. So I'd say one of the Markdown transformations would be replacing the shortcode with a custom Vue component.

**Comment by Siilwyn** [comment]
If we switch to Docusaurus we can add a markdown transformation to replace the Vue component notation right? Won't be much different from parsing shortcodes.

**Comment by jbmoelker** [comment]
Closing in favour of #45
