### ISSUE TITLE
Add YouTube video & playlist support

### ISSUE THREAD

**Issue by jbmoelker** [voorhoede/playbook#45]
Dropbox Paper shows YouTube videos as video widgets in the Paper UI. When a Paper document is exported as Markdown these videos end up as a plain URL on a new line:

```markdown
... some text.

https://www.youtube.com/watch?v=SBjQ9tuuTJQ

Next paragraph of ...
```

I'd like these plain YouTube URLs to become responsive video widgets in our Playbook. And I'd like the same to happen to YouTube playlists like `https://www.youtube.com/playlist?list=PL597E0BDDC1D74ED2`, so we can use those for our code talk and monthly update series.

Notes: 
* Maybe we can use [linkify-it](https://github.com/markdown-it/linkify-it) or [markdown-it-for-inline](https://github.com/markdown-it/markdown-it-for-inline), @Siilwyn has some experience with both.
* Maybe we can adapt the [responsive video component from the Lean Web Kit](https://github.com/voorhoede/lean-web-kit/tree/master/src/client/components/responsive-video)?
* I created an issue earlier suggesting to use shortcodes (#37). But as @Siilwyn points out this is probably a bad idea.

**Comment by Siilwyn** [comment]
Changing the link to a different html block is pretty difficult, overriding the token (`token = { ... }`) doesn't work and `token.setAttr('tag', 'span')` neither. :thinking: I guess that is why all existing solutions out there, [most popular markdown-it-video](https://www.npmjs.com/package/markdown-it-video) use their own syntax `@[youtube](dQw4w9WgXcQ)`.
