### ISSUE TITLE
Do not dump sidebar data instead use async configuration

### ISSUE THREAD

**Issue by Siilwyn** [voorhoede/playbook#65]
Now that Vuepress supports exporting an async configuration: https://github.com/vuejs/vuepress/issues/1185

**Comment by MartinMuzatko** [comment]
I've been so deep in the rabbit hole already :D 
The problem is, that the config gets transformsed into a pure reactive Vue data object/instance. It might be possible though to use a computed property.

**Comment by Siilwyn** [comment]
Closed by the vuepress-paper split: https://github.com/voorhoede/vuepress-paper/commit/bbcf4c982a7cfd225ef3358f6d72136342163971
